# Generated by Django 4.2.5 on 2023-12-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_category_ru',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
