# Generated by Django 4.2 on 2023-12-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_overview_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='article',
            field=models.TextField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_store.product'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
