# Generated by Django 4.2 on 2023-12-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0006_alter_characteristics_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='article',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
